version: "3"

services:
  db:
    image: mariadb:latest
    volumes:
      - ./db/data_dump:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=maria
      - MYSQL_PASSWORD=pass

  py-srv:
    build: py-srv
    ports:
      - "80:8080"
    depends_on:
      - db
    links:
      - "db:db"
    command: sh -c "/wait && python app.py"
    environment:
      - WAIT_HOSTS=db:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
